"""add user token_version

Revision ID: 9fb6b0dbbec0
Revises: 4b8fafa0f283
Create Date: 2026-08-07 07:30:40.712969
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '9fb6b0dbbec0'
down_revision: str | None = '4b8fafa0f283'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default keeps existing rows valid when adding a NOT NULL column.
    op.add_column(
        'users',
        sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
