import {test, expect} from "@playwright/test";

test("appointments reschedule cancel reactivate and delete", async ({page}, info) => {
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto("/register");
  await page.getByPlaceholder("Nume complet").fill("Programări Fictive");
  await page.getByPlaceholder("Email", {exact:true}).fill(`appointments-${Date.now()}-${info.project.name}@example.com`);
  await page.getByPlaceholder("Parolă (min. 8 caractere)").fill("Testing-pass-123!");
  await page.getByRole("button", {name:"Creează cont", exact:true}).click();
  await expect(page).toHaveURL(/dashboard/);
  await page.goto("/appointments");
  await page.getByLabel("Titlul programării").fill("Consultație fictivă");
  await page.getByLabel("Data și ora locală").fill("2030-05-01T10:00");
  await page.getByLabel("Sfârșit (opțional)").fill("2030-05-01T11:00");
  await page.getByLabel("Locație", {exact:true}).fill("Locație fictivă");
  await page.getByRole("button", {name:"Salvează programarea"}).click();
  await expect(page.getByRole("heading", {name:"Consultație fictivă",exact:true})).toBeVisible();
  await page.getByRole("button", {name:"Reprogramează",exact:true}).click();
  await expect(page.getByLabel("Data și ora locală")).toHaveValue("2030-05-01T10:00");
  await page.getByLabel("Data și ora locală").fill("2030-05-02T11:00");
  await page.getByLabel("Sfârșit (opțional)").fill("2030-05-02T12:00");
  await page.getByRole("button", {name:"Salvează programarea"}).click();
  await expect(page.getByRole("button", {name:"Reprogramează",exact:true})).toBeEnabled();
  await page.reload();
  await page.getByRole("button", {name:"Reprogramează",exact:true}).click();
  await expect(page.getByLabel("Data și ora locală")).toHaveValue("2030-05-02T11:00");
  await page.getByRole("button", {name:"Renunță la modificare"}).click();
  await page.getByRole("button", {name:"Anulează programarea",exact:true}).click();
  await expect(page.getByText("Anulată", {exact:true})).toBeVisible();
  await page.getByRole("button", {name:"Reactivează programarea"}).click();
  await expect(page.getByText("Programată", {exact:true})).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByRole("button", {name:"Șterge",exact:true}).click();
  await page.getByRole("button", {name:"Păstrează programarea"}).click();
  await page.getByRole("button", {name:"Șterge",exact:true}).click();
  await page.getByRole("button", {name:"Confirmă ștergerea",exact:true}).click();
  await expect(page.getByText("Nicio programare", {exact:true})).toBeVisible();
  await page.goto("/settings");
  await page.getByRole("button", {name:"Șterge contul",exact:true}).click();
  await page.getByPlaceholder("Parola", {exact:true}).fill("Testing-pass-123!");
  await page.getByRole("button", {name:"Confirmă ștergerea",exact:true}).click();
  await expect(page).toHaveURL(/login\?deleted=complete/);
  expect(errors).toEqual([]);
});
