import {test, expect} from "@playwright/test";

test("manual lab create correction and confirmed deletion", async ({page}, info) => {
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto("/register");
  await page.getByPlaceholder("Nume complet").fill("Analize Fictive");
  await page.getByPlaceholder("Email", {exact:true}).fill(`labs-${Date.now()}-${info.project.name}@example.com`);
  await page.getByPlaceholder("Parolă (min. 8 caractere)").fill("Testing-pass-123!");
  await page.getByRole("button", {name:"Creează cont", exact:true}).click();
  await expect(page).toHaveURL(/dashboard/);
  await page.goto("/labs");
  await page.getByRole("button", {name:"Adaugă rezultat",exact:true}).click();
  await page.getByLabel("Denumirea analizei").fill("Analit fictiv");
  await page.getByLabel("Valoare numerică").fill("120");
  await page.getByLabel("Unitate", {exact:true}).fill("mg/dL");
  await page.getByLabel("Limita inferioară").fill("70");
  await page.getByLabel("Limita superioară").fill("99");
  await page.getByLabel("Data recoltării").fill("2026-01-10");
  await page.getByRole("checkbox").check();
  await page.getByRole("button", {name:"Salvează rezultatul"}).click();
  await expect(page.getByText("Crescut", {exact:true})).toBeVisible();
  await page.getByRole("button", {name:"Corectează",exact:true}).click();
  await page.getByLabel("Valoare numerică").fill("85");
  await page.getByRole("checkbox").check();
  await page.getByRole("button", {name:"Salvează rezultatul"}).click();
  await expect(page.getByText("În interval", {exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByText("În interval", {exact:true})).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByRole("button", {name:"Șterge",exact:true}).click();
  await page.getByRole("button", {name:"Păstrează rezultatul"}).click();
  await expect(page.getByText("În interval", {exact:true})).toBeVisible();
  await page.getByRole("button", {name:"Șterge",exact:true}).click();
  await page.getByRole("button", {name:"Confirmă ștergerea",exact:true}).click();
  await expect(page.getByText("Nu ai analize încă", {exact:true})).toBeVisible();
  await page.goto("/settings");
  await page.getByRole("button", {name:"Șterge contul",exact:true}).click();
  await page.getByPlaceholder("Parola", {exact:true}).fill("Testing-pass-123!");
  await page.getByRole("button", {name:"Confirmă ștergerea",exact:true}).click();
  await expect(page).toHaveURL(/login\?deleted=complete/);
  expect(errors).toEqual([]);
});
