import {test,expect} from "@playwright/test";

test("explicit daily reminder lifecycle and notification inbox",async({page},info)=>{
  const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
  await page.goto("/register");
  await page.getByPlaceholder("Nume complet").fill("Memento Fictiv");
  await page.getByPlaceholder("Email",{exact:true}).fill(`reminder-${Date.now()}-${info.project.name}@example.com`);
  await page.getByPlaceholder("Parolă (min. 8 caractere)").fill("Testing-pass-123!");
  await page.getByRole("button",{name:"Creează cont",exact:true}).click();
  await expect(page).toHaveURL(/dashboard/);
  await page.goto("/medications");
  await page.getByRole("button",{name:"Adaugă tratament"}).click();
  await page.getByLabel("Denumire",{exact:true}).fill("Tratament pentru test memento");
  await page.getByLabel("Data de început").fill("2030-01-01");
  await page.getByRole("button",{name:"Salvează tratamentul"}).click();
  await page.getByRole("button",{name:"Memento-uri",exact:true}).click();
  await page.getByLabel("Ora zilnică",{exact:true}).fill("09:15");
  await page.getByLabel("Fus orar",{exact:false}).fill("Europe/Bucharest");
  await page.getByRole("button",{name:"Adaugă ora de memento",exact:true}).click();
  await expect(page.getByText("Zilnic la 09:15 · Europe/Bucharest · Activat",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Schimbă ora",exact:true}).click();
  await page.getByLabel("Ora zilnică",{exact:true}).fill("10:15");
  await page.getByRole("button",{name:"Salvează ora",exact:true}).click();
  await expect(page.getByText("Zilnic la 10:15 · Europe/Bucharest · Activat",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Pauză memento",exact:true}).click();
  await expect(page.getByText("Zilnic la 10:15 · Europe/Bucharest · În pauză",{exact:true})).toBeVisible();
  await page.reload();
  await page.getByRole("button",{name:"Memento-uri",exact:true}).click();
  await expect(page.getByRole("button",{name:"Activează memento",exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Activează memento",exact:true}).click();
  await expect(page.getByRole("button",{name:"Pauză memento",exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
  await page.screenshot({path:`../docs/screenshots/medication-reminders-${info.project.name}.png`,fullPage:true,animations:"disabled"});
  await page.getByRole("button",{name:"Comută tema"}).click();
  await expect(page.locator("html")).toHaveClass(/dark/);
  await page.screenshot({path:`../docs/screenshots/medication-reminders-dark-${info.project.name}.png`,fullPage:true,animations:"disabled"});
  await page.goto("/notifications");
  await page.getByRole("button",{name:/Viitoare/}).click();
  await expect(page.getByText("Memento ales: Tratament pentru test memento",{exact:true})).toBeVisible();
  await page.getByRole("link",{name:"Deschide medicația",exact:true}).click();
  await page.getByRole("button",{name:"Memento-uri",exact:true}).click();
  await page.getByRole("button",{name:"Șterge memento",exact:true}).click();
  await page.getByRole("button",{name:"Păstrează memento-ul",exact:true}).click();
  await page.getByRole("button",{name:"Șterge memento",exact:true}).click();
  await page.getByRole("button",{name:"Confirmă ștergerea memento-ului",exact:true}).click();
  await expect(page.getByRole("button",{name:"Schimbă ora",exact:true})).toHaveCount(0);
  await page.goto("/notifications");
  await page.getByRole("button",{name:/Toate/}).click();
  await expect(page.getByText("Nicio notificare în această categorie",{exact:true})).toBeVisible();
  await page.goto("/settings");
  await page.getByRole("button",{name:"Șterge contul",exact:true}).click();
  await page.getByPlaceholder("Parola",{exact:true}).fill("Testing-pass-123!");
  await page.getByRole("button",{name:"Confirmă ștergerea",exact:true}).click();
  await expect(page).toHaveURL(/login\?deleted=complete/);
  expect(errors).toEqual([]);
});
