import {test, expect} from "@playwright/test";

test("medication correction history and confirmed deletion", async ({page}, info) => {
  const errors: string[] = []; page.on("pageerror", e => errors.push(e.message));
  await page.goto("/register");
  await page.getByPlaceholder("Nume complet").fill("Tratamente Fictive");
  await page.getByPlaceholder("Email", {exact:true}).fill(`medications-${Date.now()}-${info.project.name}@example.com`);
  await page.getByPlaceholder("Parolă (min. 8 caractere)").fill("Testing-pass-123!");
  await page.getByRole("button", {name:"Creează cont", exact:true}).click();
  await expect(page).toHaveURL(/dashboard/);
  await page.goto("/medications");
  await page.getByRole("button", {name:"Adaugă tratament"}).click();
  await page.getByLabel("Denumire", {exact:true}).fill("Tratament fictiv");
  await page.getByLabel("Doza din prescripție").fill("Doză fictivă");
  await page.getByLabel("Frecvența din prescripție").fill("Frecvență fictivă");
  await page.getByLabel("Data de început").fill("2030-05-01");
  await page.getByLabel("Data de sfârșit").fill("2029-05-01");
  await page.getByRole("button", {name:"Salvează tratamentul"}).click();
  await expect(page.getByRole("main").getByRole("alert")).toContainText("Data de sfârșit");
  await expect(page.getByLabel("Denumire", {exact:true})).toHaveValue("Tratament fictiv");
  await page.getByLabel("Data de sfârșit").fill("2030-05-10");
  await page.getByRole("button", {name:"Salvează tratamentul"}).click();
  await expect(page.getByRole("heading", {name:"Tratament fictiv",exact:true})).toBeVisible();
  await page.getByRole("button", {name:"Verifică lista activă"}).click();
  await expect(page.getByText(/Acest rezultat nu confirmă siguranța combinației/)).toBeVisible();
  await page.getByRole("button", {name:"Corectează",exact:true}).click();
  await page.getByLabel("Doza din prescripție").fill("Doză fictivă corectată");
  await page.getByRole("button", {name:"Salvează tratamentul"}).click();
  await expect(page.getByText("Doză înregistrată: Doză fictivă corectată", {exact:true})).toBeVisible();
  await expect(page.getByRole("heading", {name:"Verificare limitată",exact:true})).toHaveCount(0);
  await page.getByRole("button", {name:"Mută în istoric",exact:true}).click();
  await expect(page.getByText("Niciun tratament activ înregistrat", {exact:true})).toBeVisible();
  await page.getByRole("button", {name:"Istoric",exact:true}).click();
  await expect(page.getByRole("heading", {name:"Tratament fictiv",exact:true})).toBeVisible();
  await page.reload();
  await page.getByRole("button", {name:"Istoric",exact:true}).click();
  await expect(page.getByText("Doză înregistrată: Doză fictivă corectată", {exact:true})).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByRole("button", {name:"Șterge",exact:true}).click();
  await page.getByRole("button", {name:"Păstrează înregistrarea"}).click();
  await page.getByRole("button", {name:"Șterge",exact:true}).click();
  await page.getByRole("button", {name:"Confirmă ștergerea",exact:true}).click();
  await expect(page.getByText("Niciun tratament în istoric", {exact:true})).toBeVisible();
  await page.goto("/settings");
  await page.getByRole("button", {name:"Șterge contul",exact:true}).click();
  await page.getByPlaceholder("Parola", {exact:true}).fill("Testing-pass-123!");
  await page.getByRole("button", {name:"Confirmă ștergerea",exact:true}).click();
  await expect(page).toHaveURL(/login\?deleted=complete/);
  expect(errors).toEqual([]);
});
